server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://120.26.107.127:3306/cloud_user?useSSL=false
    username: eric
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    #user服务的名称
    name: user-service
  cloud:
    nacos:
      server-addr: 120.26.107.127:8848
      discovery:
        cluster-name: SH # 集群名称
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
#eureka:
#  client:
#    service-url:
#      # eureka的地址信息
#      defaultZone: http://localhost:10086/eureka
